name: Continuous Integration (CI)

# Run CI jobs on all branches by default
on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Test with Gradle Wrapper
        run: ./gradlew test

      - name: Generate JaCoCo Test Report
        run: ./gradlew jacocoTestReport
